
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 30
    service-url:
      defaultZone: http://localhost:8080/eureka/
    
      instance:
        hostname: localhost
          
      
 